version: "3.7"
services:
    react_app:
        build:
            context: ./react_app
            dockerfile: Dockerfile
        ports:
          - "3000:3000"
        volumes:
          - ./react_app:/usr/src/app
        depends_on:
          - spring-boot
        environment:
          PORT: 3000
          PROXY_API: http://spring-boot-app:8080
        networks:
          - my_network

    spring-boot:
        build:
          context: ./spring-boot
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
        depends_on:
          - jobmanager
          - taskmanager
          # - zookeeper
          # - kafka
        networks:
          - my_network  
      
    python_script_rand:
        build:
          context: ./scripts/script2
          dockerfile: Dockerfile
        networks:
          - my_network
        depends_on:
          - spring-boot
        ports:
          - "8082:8080"
        environment:
          PORT: 8082
          PROXY_API: http://spring-boot:8080/earthquakes
      
    python_script_input:
        build:
          context: ./scripts/script1
          dockerfile: Dockerfile
        networks:
          - my_network
        command: bash -c "python input_data.py"
        depends_on:
          - spring-boot
        ports:
          - "8083:8080"
        environment:
          PORT: 8083
          PROXY_API: http://spring-boot:8080/earthquakes
        stdin_open: true
        tty: true

    jobmanager:
        image: flink:latest
        environment:
          - |
            FLINK_PROPERTIES=
            jobmanager.rpc.address: jobmanager
        ports:
          - "8081:8081"
        volumes:
          - ./settings/:/settings
          - ./data/:/data
        command: jobmanager
        networks:
          - my_network

    taskmanager:
        image: flink:latest
        volumes:
          - ./settings/:/settings
          - ./data/:/data
        environment:
          - |
            FLINK_PROPERTIES=
            jobmanager.rpc.address: jobmanager
            taskmanager.numberOfTaskSlots: 10
        depends_on:
              - jobmanager
        command: taskmanager
        networks:
          - my_network

    # zookeeper:
    #     image: wurstmeister/zookeeper
    #     ports:
    #       - "2181:2181"
    # kafka:
    #   image: wurstmeister/kafka
    #   ports:
    #     - "9092:9092"
    #   environment:
    #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

networks:
  my_network:
    driver: bridge